services:
  backend:
    env_file:
      - .env
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: job-board-backend
    ports:
      - "8000:8000"
    environment:
      DATABASE_URL: postgresql://postgres:${POSTGRES_PASSWORD}@db:${DATABASE_PORT}/job-board
      REDIS_URL: ${REDIS_URL}
    volumes:
      - ./backend:/app
    depends_on:
      db:
        condition: service_healthy
      redis:
        condition: service_started
    networks:
      - job_board_network
    # profiles: ["backend"]

  tests:
    env_file:
        - .env
    build:
        context: ./backend
    volumes:
        - ./backend:/app
    depends_on:
        db:
            condition: service_healthy
        redis:
            condition: service_started
    environment:
        DJANGO_SETTINGS_MODULE: backend.config.settings
        DATABASE_HOST: ${DATABASE_HOST}
        DATABASE_PORT: ${DATABASE_PORT}
        POSTGRES_DB: ${POSTGRES_DB}
        POSTGRES_USER: ${POSTGRES_USER}
        POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
        REDIS_URL: ${REDIS_URL}
    command: pytest
    profiles: ["test"]
  db:
    env_file:
      - .env
    image: postgres:15
    container_name: job-board-db
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    ports:
      - "5430:5432" # optional
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres -d job-board"]
      interval: 5s
      timeout: 5s
      retries: 5
    networks:
      - job_board_network

  redis:
    image: redis:7
    container_name: job-board-redis
    volumes:
      - redis_data:/data
    networks:
      - job_board_network

volumes:
  postgres_data:
  redis_data:

networks:
  job_board_network:
    driver: bridge
